# Generated by Django 6.0.2 on 2026-03-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardName', models.CharField(max_length=100)),
                ('wardNumber', models.IntegerField()),
                ('floor', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('Ward', models.CharField(choices=[('ICU', 'ICU'), ('General', 'General'), ('Private', 'Private'), ('Emergency', 'Emergency'), ('OT', 'OT'), ('Maternity', 'Maternity')], max_length=9)),
                ('description', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
            ],
        ),
    ]
