# Generated by Django 6.0.2 on 2026-03-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ward', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_ward',
            old_name='Ward',
            new_name='department',
        ),
    ]
