# Generated by Django 6.0.2 on 2026-03-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ward', '0002_rename_ward_add_ward_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_Ward',
            new_name='addWard',
        ),
    ]
