# Generated by Django 6.0.2 on 2026-03-10 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ward', '0003_rename_add_ward_addward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('addWard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ward.addward')),
            ],
        ),
    ]
