# Generated by Django 6.0.2 on 2026-03-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ward', '0004_bed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='addWard',
            new_name='ward',
        ),
    ]
