# Generated by Django 6.0.2 on 2026-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.IntegerField(max_length=3)),
                ('Mobileno', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('ward', models.CharField(max_length=30)),
                ('Problem', models.CharField(max_length=150)),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
