# Generated by Django 6.0.2 on 2026-02-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patient',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_patient',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='add_patient',
            name='Mobileno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_patient',
            name='ward',
            field=models.CharField(choices=[('ICU', 'ICU'), ('General', 'General'), ('Private', 'Private'), ('Emergency', 'Emergency'), ('OT', 'OT'), ('Maternity', 'Maternity')], max_length=9),
        ),
    ]
