# Generated by Django 6.0.2 on 2026-02-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_add_patient_age_alter_add_patient_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_patient',
            old_name='ward',
            new_name='Ward',
        ),
    ]
