# Generated by Django 6.0.2 on 2026-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_rename_ward_add_patient_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
