# Generated by Django 6.0.2 on 2026-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_add_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Specialization', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Experience', models.IntegerField(max_length=100)),
                ('Mobileno', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Ward', models.CharField(choices=[('ICU', 'ICU'), ('General', 'General'), ('Private', 'Private'), ('Emergency', 'Emergency'), ('OT', 'OT'), ('Maternity', 'Maternity')], max_length=9)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
            ],
        ),
    ]
