# Generated by Django 6.0.2 on 2026-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_add_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doctor',
            name='Experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_doctor',
            name='Specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Gynecologist', 'Gynecologist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('ENT Specialist', 'ENT Specialist'), ('General Physician', 'General Physician')], max_length=18),
        ),
    ]
