# Generated by Django 6.0.2 on 2026-02-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_alter_add_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doctor',
            name='Experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
