# Generated by Django 6.0.2 on 2026-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_alter_add_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doctor',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_doctor',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
