# Generated by Django 6.0.2 on 2026-02-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_alter_add_doctor_available_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_doctor',
            old_name='available_from',
            new_name='Available_from',
        ),
        migrations.RenameField(
            model_name='add_doctor',
            old_name='available_to',
            new_name='Available_to',
        ),
    ]
