# Generated by Django 6.0.2 on 2026-02-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_rename_available_from_add_doctor_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doctor',
            name='Available_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='add_doctor',
            name='Available_to',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='add_doctor',
            name='Experience',
            field=models.IntegerField(null=True),
        ),
    ]
