# Generated by Django 6.0.2 on 2026-03-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ward', '0004_bed'),
        ('admission', '0011_alter_add_doctor_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_patient',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ward.bed'),
        ),
        migrations.AlterField(
            model_name='add_patient',
            name='Ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ward.addward'),
        ),
    ]
